### ISSUE TITLE
vuzzer64 cannot detect crash

### ISSUE THREAD

**Issue by wendy23git** [vusec/vuzzer64#10]
Hi, I really appreciate your work on VUzzer and VUzzer64. However, when I use VUzzer64 to fuzz some programs such as mp3gain, exiv2, LAVA-M on Ubuntu 16.04, 64 bits, I haven't found any crash on them. I think the code which determine whether an input cause a crash may be wrong in VUzzer64. 
In runfuzzer.py, 
the code:
`if retc < 0 and retc != -2:`
may should be changed into:
`if retc <0 or (retc>128 and retc<(128+64))`
Thanks.

**Comment by tosanjay** [comment]
Hi,
Sorry about not being able to respond. I have just relocated to a different country and trying to settling in. I will get back to it ASAP. meanwhile, have a look at python subprocess module for return code.

**Comment by wendy23git** [comment]
For vuzzer, the code for determing crash is right as it leverages python subprocess to get exit code (retc <0 and retc!=2).
However,
as VUzzer64 use shell to get the exit code, the return code should be more than 128.

**Comment by MoonLight-SteinsGate** [comment]
I have found the same mistake. The return value of executing some crashes input is more than 128, exactly 139. 

So I modified the source code of runfuzzer.py according to the method by @tosanjay. After that, VUzzer64 can detect the crashes. However, it seems that it could not recognize the unique crashes. After some time of fuzzing base64 of LAVA-M (about 2 hours), it only detects one unique crash in the outd directory. Some output information is shown below:
```
[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-374-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-373-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-372-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-371-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-370-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-369-g10.b64']
[*] Run complete..
```

**Comment by MoonLight-SteinsGate** [comment]
I have found the same mistake. The return value of executing some crashes input is more than 128, exactly 139.

So I modified the source code of runfuzzer.py according to the method by @wendy23git. After that, VUzzer64 can detect the crashes. However, it seems that it could not recognize the unique crashes. After some time of fuzzing base64 of LAVA-M (about 2 hours), it only detects one unique crash in the outd directory. Some output information is shown below:
```
[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-166-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-165-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-164-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-163-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-162-g10.b64']
[*] Run complete..

[*]Error code is 139
[*] Just about to run  ['BBOUT=/home/moonlight/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/home/moonlight/LAVA-M/base64', '-d', '/home/moonlight/vuzzer64/fuzzer-code/vutemp/data/new-161-g10.b64']
[*] Run complete..
```

**Comment by tosanjay** [comment]
Thanks @wendy23git. I forgot to mention that i fixed the code sometime ago. closing the issue.
