### ISSUE TITLE
Source Code for 64-bit

### ISSUE THREAD

**Issue by pratikbhd** [vusec/vuzzer64#2]
I am looking for the 64-bit version of vuzzer but only found the code for the 32-bit one. Any idea when the 64-bit version will be available?
Thanks!

**Comment by tosanjay** [comment]
Hi, I am planning to release it in 1 week time. Thanks for your interest.RegardsSanjay

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 3, 2018 at 23:39, Pratik Bhandari<notifications@github.com> wrote:   
I am looking for the 64-bit version of vuzzer but only found the code for the 32-bit one. Any idea when the 64-bit version will be available?
Thanks!

**Comment by pratikbhd** [comment]
Awesome! I'll be looking forward to it. Thanks!

**Comment by tosanjay** [comment]
released.
