### ISSUE TITLE
`make tools` failed in libdft64

### ISSUE THREAD

**Issue by Ricardio609** [vusec/vuzzer64#24]
https://github.com/vusec/vuzzer64/blob/2b1b0ed757a3dca114db0192fa4ab1add92348bc/libdft64/INSTALL#L28
get the error "make: Nothing to be done for 'tools' ", when `make tools`
![image](https://user-images.githubusercontent.com/64991294/146334151-e1ae1259-1798-4c2a-b6b5-9687ef7e23b2.png)

**Comment by tosanjay** [comment]
Foolow the instruction which are in the main README (in the home directory):
0. cd vuzzer64
1. export PIN_HOME=path_to_pin_directory
2. export PIN_ROOT=path_to_pin_directory
3. export DFT_HOME=$(pwd)/libdft64
4. cd fuzzer-code
5. make
6. cd ../libdft64
7. make
9. cd ..

**Comment by Ricardio609** [comment]
Hi, tosanjay. what should I do if I want to make libdft alone?

**Comment by tosanjay** [comment]
This |
       V

cd ../libdft64
make
