### ISSUE TITLE
How to use libdft from vuzzer64 to get the relation of input bytes and branch under execution?

### ISSUE THREAD

**Issue by Ricardo-609** [vusec/vuzzer64#26]
what should I do if I want to use libdft from vuzzer64 for getting the relation of input bytes and branch under execution? Can anyone help me？

**Comment by tosanjay** [comment]
It is easy if you are just interested in knowing which input bytes affect your target branch-- when you run your application with VUzzer (internally with libdft pintool), it creates a file called cmp.log. this file contains info for each cmp instruction executed by the application on that input. IMP: you can directly execute this pintool outside of VUzzer and get the cmp.log file (in some of the issues, i explained how to do that. just search).

**Comment by Ricardio609** [comment]
hi,tosanjay. I'm not sure wether you said is https://github.com/vusec/vuzzer64/issues/9#issuecomment-474956390. Followed the instruction,  I can't find cmp.log, it only generate three file`cmp.out lea.out pintool.log`.  

I'm not sure how to use the command  parameter ` -filename $2 `. Is it input as taint ? I use the file named in, but it still need to input manually. And both lea.out and cmp.out are empty when use `./in`.
![image](https://user-images.githubusercontent.com/64991294/147383874-a436923a-70d1-4753-acb6-c5a46f41351f.png)
Hope to hear from your anwer.Thanks.

**Comment by tosanjay** [comment]
Yes, it is cmp.out. sorry. if they are empyy it means pin did not run on your binary (yes, issue #9 is the one.). 
From the command line, i can see the you are running ./hw with no parameter. how do you run hw normally? you have to use the same commandline here with input_file place holder as %s. If you are used to AFL, you use @@ for the same purpose.

**Comment by Ricardio609** [comment]
Thanks, @tosanjay. I have successfully generated cmp.out like below.
```
64 mem reg 0x00007f336ff4cc58 {} {} {} {} {} {} {} {} {0} {1} {2} {3} {4} {5} {6} {7} 0x10102464c457f 0x3010102464c457f 
64 mem reg 0x00007f336ff4cfb8 {} {} {} {} {} {} {} {} {0} {1} {2} {3} {4} {5} {6} {7} 0x3010102464c457f 0x3010102464c457f 
32 mem reg 0x00007f336ff4cc77 {9} {10} {11} {12} {} {} {} {} {} {} {} {} {} {} {} {} 0x0 0x0 
16 mem reg 0x00007f336ff4ccd7 {13} {14} {} {} {} {} {} {} {} {} {} {} {} {} {} {} 0x0 0x0 
8 mem reg 0x00007f336ff4cce4 {15} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} 0x0 0x0 
```
But `cmp.out ` is empty when command without `-filename`. And where could i retrive meaning abou each colunms of cmp.out ? 
Thanks again!

**Comment by tosanjay** [comment]
you need to provide required option to run a tool in a particular way, thus -filename option is needed (this is how it is designed).

each line of cmp.out tells:
operation size, 1st operand type, 2nd operand type, address of the cmp instruction, {taint bytes} affecting the 8 bytes of 1st operand, {taint bytes} affecting the 8 bytes 2nd operand, concrete value of 1st operand,  concrete value of 2nd operand
