### ISSUE TITLE
`Filename for which we need to track taint`

### ISSUE THREAD

**Issue by Ricardo-609** [vusec/vuzzer64#27]
https://github.com/vusec/vuzzer64/blob/2b1b0ed757a3dca114db0192fa4ab1add92348bc/libdft64/tools/libdft-dta.cpp#L64
Filesize for which we need to track taint?

**Comment by tosanjay** [comment]
aha.. thats clearly a wrong description. it is about how many different labels we want to track for a single byte. if the operand of a cmp depends on too many input bytes, we can't do a meaningful mutation any way. you can change it based on your requirements.
